//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentPlant.BackgroundTasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventSourceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventSourceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentPlant.BackgroundTasks.EventSourceResources", typeof(EventSourceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Work Items.
        /// </summary>
        internal static string Counter_CompletedWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_CompletedWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed-work-items.
        /// </summary>
        internal static string Counter_CompletedWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_CompletedWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faulted Work Items.
        /// </summary>
        internal static string Counter_FaultedWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_FaultedWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faulted-work-items.
        /// </summary>
        internal static string Counter_FaultedWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_FaultedWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Pending Work Items.
        /// </summary>
        internal static string Counter_QueueSize_DisplayName {
            get {
                return ResourceManager.GetString("Counter_QueueSize_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to queue-size.
        /// </summary>
        internal static string Counter_QueueSize_Name {
            get {
                return ResourceManager.GetString("Counter_QueueSize_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Running Work Items.
        /// </summary>
        internal static string Counter_RunningWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_RunningWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to running-work-items.
        /// </summary>
        internal static string Counter_RunningWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_RunningWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Completed Work Items.
        /// </summary>
        internal static string Counter_SuccessfulWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_SuccessfulWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful-work-items.
        /// </summary>
        internal static string Counter_SuccessfulWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_SuccessfulWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Completed Work Items.
        /// </summary>
        internal static string Counter_TotalCompletedWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_TotalCompletedWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total-completed-work-items.
        /// </summary>
        internal static string Counter_TotalCompletedWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_TotalCompletedWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Faulted Work Items.
        /// </summary>
        internal static string Counter_TotalFaultedWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_TotalFaultedWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total-faulted-work-items.
        /// </summary>
        internal static string Counter_TotalFaultedWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_TotalFaultedWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Number of Successfully Completed Work Items.
        /// </summary>
        internal static string Counter_TotalSuccessfulWorkItems_DisplayName {
            get {
                return ResourceManager.GetString("Counter_TotalSuccessfulWorkItems_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to total-successful-work-items.
        /// </summary>
        internal static string Counter_TotalSuccessfulWorkItems_Name {
            get {
                return ResourceManager.GetString("Counter_TotalSuccessfulWorkItems_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task service &apos;{0}&apos; is running..
        /// </summary>
        internal static string event_ServiceRunning {
            get {
                return ResourceManager.GetString("event_ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task service &apos;{0}&apos; has stopped..
        /// </summary>
        internal static string event_ServiceStopped {
            get {
                return ResourceManager.GetString("event_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item completed. Service: &apos;{0}&apos;, item: &apos;{1}&apos;, description: &apos;{2}&apos;, elapsed time: {3} seconds.
        /// </summary>
        internal static string event_WorkItemCompleted {
            get {
                return ResourceManager.GetString("event_WorkItemCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item dequeued. Service: &apos;{0}&apos;, item: &apos;{1}&apos;, description: &apos;{2}&apos;, queue size: {3} items.
        /// </summary>
        internal static string event_WorkItemDequeued {
            get {
                return ResourceManager.GetString("event_WorkItemDequeued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item enqueued. Service: &apos;{0}&apos;, item: &apos;{1}&apos;, description: &apos;{2}&apos;, queue size: {3} items.
        /// </summary>
        internal static string event_WorkItemEnqueued {
            get {
                return ResourceManager.GetString("event_WorkItemEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item faulted. Service: &apos;{0}&apos;, item: &apos;{1}&apos;, description: &apos;{2}&apos;, elapsed time: {3} seconds.
        /// </summary>
        internal static string event_WorkItemFaulted {
            get {
                return ResourceManager.GetString("event_WorkItemFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item running: Service: &apos;{0}&apos;, item: &apos;{1}&apos;, description: &apos;{2}&apos;.
        /// </summary>
        internal static string event_WorkItemRunning {
            get {
                return ResourceManager.GetString("event_WorkItemRunning", resourceCulture);
            }
        }
    }
}
