//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IntelligentPlant.BackgroundTasks {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EventSourceResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EventSourceResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IntelligentPlant.BackgroundTasks.EventSourceResources", typeof(EventSourceResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task service is running..
        /// </summary>
        internal static string event_ServiceRunning {
            get {
                return ResourceManager.GetString("event_ServiceRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background task service has stopped..
        /// </summary>
        internal static string event_ServiceStopped {
            get {
                return ResourceManager.GetString("event_ServiceStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item completed. ID: &apos;{0}&apos;, description: &apos;{1}&apos;, elapsed time: {2}.
        /// </summary>
        internal static string event_WorkItemCompleted {
            get {
                return ResourceManager.GetString("event_WorkItemCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item dequeued: ID: &apos;{0}&apos;, description: &apos;{1}&apos;, queue size: {2} items.
        /// </summary>
        internal static string event_WorkItemDequeued {
            get {
                return ResourceManager.GetString("event_WorkItemDequeued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item enqueued: ID: &apos;{0}&apos;, description: &apos;{1}&apos;, queue size: {2} items.
        /// </summary>
        internal static string event_WorkItemEnqueued {
            get {
                return ResourceManager.GetString("event_WorkItemEnqueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item faulted. ID: &apos;{0}&apos;, description: &apos;{1}&apos;, elapsed time: {2}.
        /// </summary>
        internal static string event_WorkItemFaulted {
            get {
                return ResourceManager.GetString("event_WorkItemFaulted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work item running: ID: &apos;{0}&apos;, description: &apos;{1}&apos;.
        /// </summary>
        internal static string event_WorkItemRunning {
            get {
                return ResourceManager.GetString("event_WorkItemRunning", resourceCulture);
            }
        }
    }
}
